### ISSUE TITLE
POST to https://tapi.telstra.com/v2/messages/sms returns error

### ISSUE THREAD

**Issue by siquick** [telstra/MessagingAPI-v2#1]
When using Python requests library I get the following error:

```
{
		        "status":"500",
				"code":"TECH-ERR",
				"message":"Technical error : JSONThreatProtection[cp_JSONThreatProtection.DoSAEvaluation]: Execution failed. reason: Expecting { or [ at line 1 : An error has occurred while processing your request, please refer to API Docs for summary on the issue"
			  }
```

Example POST to `https://tapi.telstra.com/v2/messages/sms`

```
headers = {'Content-Type': 'application/json', 'Authorization': 'Bearer abc12345678'}
payload = {'body': 'hi there', 'to': '+61429123123'}
```

**Comment by developersteve** [comment]
Hi @siquick, 

The SDKs have been updated and moved to separate repos, check here for the latest Python sdk https://github.com/telstra/MessagingAPI-SDK-python 

Also that payload needs some more fields added to it...

```
payload = {'to': '000000000000',
    'body': 'Hello World',
    'from': '000000000000',
    'validity': 1,
    'scheduledDelivery': 60,
    'notifyURL': '',
    'replyRequest': 'false'}
```

**Comment by siquick** [comment]
Hi @developersteve

Thanks for that

Is it a requirement to use the SDK? I've followed everything here and would prefer to interact with the APIs directly https://github.com/telstra/MessagingAPI-v2/blob/master/Getting%20Started.md

Thanks!

**Comment by developersteve** [comment]
Yup thats cool you can message it directly, thought you might have been trying to use one of the SDKs that were previously in the repo. 

The other thing then if you are using requests.post is to make sure that the payload is being sent as json and not data (unless you are converting the body to json).  

as of 2.4.2 requests you can specify json instead 

```
requests.post(url, json=payload, headers=header)
```

**Comment by siquick** [comment]
Thanks Steve, still no joy unfortunately

Here's some output

----Headers----
```
<type 'dict'>
{'Content-Type': 'application/json', 'Authorization': 'Bearer ABCDEFGHJK123456'}
```

----Payload----
```
<type 'dict'>
{'body': 'hello world', 'scheduledDelivery': '60', 'replyRequest': 'false', 'from': '0123456789', 'notifyURL': '', 'validity': '1', 'to': '0123456789'}
```

`send_url = 'https://tapi.telstra.com/v2/messages/sms'`

`send_post = requests.post(send_url,headers=send_headers,json=send_payload)`

----Output----
```
{
		        "status":"500",
				"code":"TECH-ERR",
				"message":"Technical error : Execution of JS.ModifyMessageIdURLResponse failed with error: Javascript runtime error: \"TypeError: Cannot call method \"map\" of undefined. (modifyMessageIdURLResponse.js:57)\" : An error has occurred while processing your request, please refer to API Docs for summary on the issue"
			  }
```

Have also tried with `send_post = requests.post(send_url,headers=send_headers,data=json.dumps(send_payload))`

Same error occurs from Postman

**Comment by developersteve** [comment]
Have you provisioned a sending number against the application using provisioning/subscriptions?

**Comment by siquick** [comment]
No I hadn't and that has solved it. 

Thanks for the help Steve, appreciate it.

(maybe your team could make the errors a bit clearer?)

**Comment by developersteve** [comment]
Ah awesome, yep flagged that one with them.
