### ISSUE TITLE
Provisional error(404)

### ISSUE THREAD

**Issue by GaurangPoolCar** [telstra/MessagingAPI-v2#10]
Got error when provision number. 

Request:
curl -X POST \
  https://tapi.telstra.com/v2/messages/provisioning/subscriptions \
  -H 'accept: application/json' \
  -H 'authorization: Bearer AccessToken' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
	"activeDays":30,
  "notifyURL":"http://example.com/callback",
  "callbackData":
  {
    "anything":"some data"
  }
}'

Response:
{
    "status": "404",
    "code": "RESOURCE-NOT-FOUND",
    "message": ""
}

**Comment by developersteve** [comment]
Hi @GaurangPoolCar, 

You need to put line breaks if you are going to curl over multiple lines, try this 

```
curl -X POST \
  https://tapi.telstra.com/v2/messages/provisioning/subscriptions \
  -H 'authorization: Bearer $ACCESS_TOKEN' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
  "activeDays":30,
  "notifyURL":"http://example.com/callback",
  "callbackData":
  {
    "anything":"some data"
  }
}'
```
Response i just got from that call with a token is 
```
{
  "destinationAddress": "+61472880343"
}
```

**Comment by GaurangPoolCar** [comment]
Hi @developersteve 

Thanks for your reply.
I tried this with Postman but same result.....

curl -X POST \
  https://tapi.telstra.com/v2/messages/provisioning/subscriptions \
  -H 'authorization: Bearer ACCESSTOKEN' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
  "activeDays":30,
  "notifyURL":"http://example.com/callback",
  "callbackData":
  {
    "anything":"some data"
  }
}'

**Comment by developersteve** [comment]
Ok think we might have worked it out, are you trying to use a token from the older v1 API or are you using creds from https://dev.telstra.com?

**Comment by GaurangPoolCar** [comment]
No, the token that I got from V2 API.

**Comment by developersteve** [comment]
ok still trying to debug but i cant replicate, can you try on another computer and connection? could there be a firewall or proxy blocking the endpoint requests for some reason?

**Comment by developersteve** [comment]
Can you please try again with the provisioning call, we identified an issue on one of the servers which should now be resolved.

**Comment by GaurangPoolCar** [comment]
Yeah. It is working now.  Thanks @developersteve
