### ISSUE TITLE
invalid_client: https://tapi.telstra.com/v2/oauth/token

### ISSUE THREAD

**Issue by GaurangPoolCar** [telstra/MessagingAPI-v2#8]
Hi,

I am following instruction mention in the doc. But got an "invalid_client" error while requesting auth token.

curl -X POST -H 'Content-Type: application/x-www-form-urlencoded'-d "grant_type=client_credentials&client_id=Client_ID&client_secret=Secret&scope=NSMS"  'https://tapi.telstra.com/v2/oauth/token'

We are currently using https://api.telstra.com/v1/oauth/token. We do not have this issue in V1 API.

**Comment by developersteve** [comment]
Hi @GaurangPoolCar, 

i just tried this and it worked for me ....

```
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' -d "grant_type=client_credentials&client_id=Client_ID&client_secret=Secret&scope=NSMS" 'https://tapi.telstra.com/v2/oauth/token'
```

theres a space needed near the -d, just about to check and update the docs if it needs it. 

Also dont forget to swap out your api key details from dev.telstra.com in the Client_ID and Secret places.

**Comment by developersteve** [comment]
Checked the docs and its got this with line breaks

```
CONSUMER_KEY="your consumer key"
CONSUMER_SECRET="your consumer secret"
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' \
  -d "grant_type=client_credentials&client_id=$CONSUMER_KEY&client_secret=$CONSUMER_SECRET&scope=NSMS" \
  'https://tapi.telstra.com/v2/oauth/token'
```
id highly recommend upgrading the endpoints as soon as you can as we are looking to depreciate the v1 api's

**Comment by GaurangPoolCar** [comment]
Hi @developersteve 

Thanks for quick response. 
I tried the curl as you mention but no luck, but when I replace API endpoint from "https://tapi.telstra.com/v2/oauth/token" to "https://api.telstra.com/v1/oauth/token" it works. So I don't know why the same curl is not working with "https://tapi.telstra.com/v2/oauth/token".

**Comment by developersteve** [comment]
@GaurangPoolCar 

hrmm, are you using apikeys from dev.telstra.com or the legacy portal at developer.telstra.com?
